### ISSUE TITLE
Set IPv4 address on interface on Windows

### ISSUE THREAD

**Issue by conradev** [hackclub/burrow#54]
We could break this up into smaller tasks – setting IP address, netmask, etc

**Comment by conradev** [comment]
https://learn.microsoft.com/en-us/windows/win32/iphlp/managing-ip-addresses-using-addipaddress-and-deleteipaddress

We would use the above API but from the Windows crate: https://github.com/microsoft/windows-rs

**Comment by LimesKey** [comment]
Is this the local LAN client's IP address and network details, such as the information here:
![image](https://github.com/hackclub/burrow/assets/85136735/1adcbbfc-88d4-44a5-a559-6ba889b4086f)
If so, yeah this is all Windows managed like you said and we can use the API. I'm wondering if I/we could use Powershell for this Windows stuff? I'm ok at Powershell and I find it a lot easier for Windows things than Rust. I don't know how to link Rust and Powershell together though.

**Comment by LimesKey** [comment]
Actually, what about this crate? https://crates.io/crates/ipconfig
This seems like all we need right?

**Comment by LimesKey** [comment]
@conradev I attempted to implement the ipconfig create in a function, but I am having 1 issue.
```rust
 pub fn ipv4_addr() -> IpAddr {
            let mut adapters = ipconfig::get_adapters().unwrap(); // get all adapaters

            adapters.sort_by_key(|a| a.ipv4_metric()); // sort by metric, note this is managed by windows, lower metric number is higher priority
            let _address = adapters[0].ip_addresses(); // get the first adapter's ip address including ipv4 and ipv6
                                                       //let ipv4_address = _address::IpAddr::V4(ip4);
                                                       //let ipv4_address = _address[1].to_string(); // 0 for ipv6, 1 for ipv4
            let ipv4_addr = IpAddr::V4(Ipv4Addr::from(_address.parse()[1]));
            _address[1]
        }
```
Specifically storing a IPV4 address from a IpAddr that contains both IPV6 and IPV4, seems relatively easy but I can't figure out the syntax for this plugin. I spent a lot of time on this but couldn't make it work but you probably can. I tested this without the part I'm having issues with, and it works great, it fetches the preset IP that has the lowest metric.

**Comment by conradev** [comment]
@LimesKey that crate does not provide the functionality we need, and does a lot of unnecessary work.  For example, it isn't a correct approach to get all addresses of all adapters on the system in order to get a single address for a single adapter.

Windows has APIs to do this, and we just need to call into them. That is what the `ipconfig` crate itself does. While the `ipconfig` crate is not directly useful to us, reading its source code might help

**Comment by LimesKey** [comment]
I realize now that I misinterpreted what the goal of the issue was, at the time I assumed we needed the client's LAN IP and networking information but now I think the goal is to create a new Windows Network Adapter to use as the VPN's tunnel. I'm trying to understand the project more as it's so big, so to assist me with this I'm comparing the project to how Wireguard does it.

Wireguard creates its own virtual network adapter within Windows, and it looks like this,
![image](https://github.com/hackclub/burrow/assets/85136735/2982c58b-7af4-4896-a52c-da2a481b7ba8)
Wireguard then sets the IPv4 address on the network adapter to the one included in the config file. The subnet mask is also here in the `/32`.
```
[Interface]
#iPhone
PrivateKey=
Address=192.168.3.2/32

[Peer]
Endpoint=example.com:443
```
Does Burrow have a config file like this? I might be able to create the virtual network adapter with the information, but where do I get this information from? I apologize for not knowing how this works.
